export { default as NavBar } from './NavBar'
export { default as Homepage } from './Homepage'
// export { default as SearchForm } from './SearchForm'
export { default as AlbumSearch } from './AlbumSearch'
export { default as Recommendations } from './Recommendations'
export { default as HipHop } from './HipHop'
export { default as Gospel } from './Gospel'
export { default as Country } from './Country'
